# Generated by Django 3.0 on 2019-12-17 05:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('prisoners', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Felony',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(verbose_name='End Date')),
                ('fine_charged', models.IntegerField(verbose_name='Fine Charged')),
                ('prisoner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prisoners.Prisoner')),
            ],
            options={
                'verbose_name': 'Felony',
                'verbose_name_plural': 'Felonies',
            },
        ),
    ]
