# Generated by Django 3.0 on 2019-12-22 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prisoners', '0002_auto_20191217_0701'),
        ('lawyers', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LawyerClients',
            new_name='LawyerClient',
        ),
    ]
