# Generated by Django 3.0 on 2019-12-16 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prisoner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Firstname')),
                ('second_name', models.CharField(max_length=50, verbose_name='Secondname')),
                ('id_number', models.CharField(max_length=50, verbose_name='Id Number')),
                ('next_kin_name', models.CharField(max_length=50, verbose_name='Name')),
                ('next_kin_id', models.CharField(max_length=50, verbose_name='Id Number')),
                ('next_kin_tel', models.IntegerField(verbose_name='Phone Number')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('fined_charges', models.IntegerField()),
                ('punishment_status', models.TextField(verbose_name='Status of punishment')),
            ],
        ),
    ]
