# Generated by Django 3.0 on 2019-12-16 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prisoner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Firstname')),
                ('last_name', models.CharField(max_length=50, verbose_name='Lastname')),
                ('id_number', models.CharField(max_length=50, verbose_name='Id Number')),
            ],
        ),
    ]
